steps:
  - label: ":pipeline: Check if directory exists and clone repository"
    command: |
      DIRECTORY_PATH=${BUILDKITE_BUILD_CHECKOUT_PATH}
      REPO_URL=${BUILDKITE_REPO}
      
      if [ -d ${BUILDKITE_BUILD_CHECKOUT_PATH} ]; then
        echo "Directory ${BUILDKITE_BUILD_CHECKOUT_PATH} already exists."
      else
        echo "Directory ${BUILDKITE_BUILD_CHECKOUT_PATH} does not exist. Cloning repository..."
        git clone ${BUILDKITE_REPO} ${BUILDKITE_BUILD_CHECKOUT_PATH}
        cd ${BUILDKITE_BUILD_CHECKOUT_PATH}
        LATEST_COMMIT=$(git rev-parse HEAD)  # Get the latest commit hash
        git checkout "$LATEST_COMMIT"
      fi
    agents:
      queue: "default-queue"


  - label: ":pipeline: Check for changes in folder"
    command: |
      FOLDER="tests"
      if [ ! -d "tests" ]; then
        echo "Error: tests does not exist or is not a directory."
        exit 1
      fi

      CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
      if git diff --quiet "main...$(git rev-parse --abbrev-ref HEAD)" -- "tests"; then
        echo "No changes in tests between $(git rev-parse --abbrev-ref HEAD) and main"
        exit 0
      else
        echo "Changes detected in tests between $(git rev-parse --abbrev-ref HEAD) and main"
        # List all files changed within the folder between the current branch and main
        CHANGED_FILES=$(git diff --name-only "main...$(git rev-parse --abbrev-ref HEAD)" -- "tests")
        # Loop through each changed file and print its content
        for file in $(git diff --name-only "main...$(git rev-parse --abbrev-ref HEAD)" -- "tests"); do
          echo "Changed file: $file"
          echo "-----------------"
          cat "$file"  # Print the content of the changed file
          echo ""
        done
      fi

  - label: ":pipeline: Echo provided environment variable"
    command: |
      if [ -z "$ENV" ]; then
        echo "Error: ENV is not provided."
        exit 1
      else
        echo "The value of ENV is: $MY_VARIABLE"
      fi
    env:
      MY_VARIABLE: "${MY_VARIABLE}"
