steps:
  - label: ":pipeline: Check if directory exists and clone repository"
    command: |
      DIRECTORY_PATH=${BUILDKITE_BUILD_CHECKOUT_PATH}
      REPO_URL=${BUILDKITE_REPO}
      
      if [ -d ${BUILDKITE_BUILD_CHECKOUT_PATH} ]; then
        echo "Directory ${BUILDKITE_BUILD_CHECKOUT_PATH} already exists."
      else
        echo "Directory ${BUILDKITE_BUILD_CHECKOUT_PATH} does not exist. Cloning repository..."
        git clone ${BUILDKITE_REPO} ${BUILDKITE_BUILD_CHECKOUT_PATH}
        cd ${BUILDKITE_BUILD_CHECKOUT_PATH}
        LATEST_COMMIT=$(git rev-parse HEAD)  # Get the latest commit hash
        git checkout "$LATEST_COMMIT"
      fi
    agents:
      queue: "default-queue"


  - label: ":pipeline: Check for changes in folder"
    command: |
      # Set up any necessary environment variables or configurations
      # For example, set AWS credentials or other required variables

      # Check if there are changes in the repository
      if ! git diff --quiet HEAD~1 HEAD; then
        # List all files changed between HEAD~1 and HEAD
        CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)

        # Loop through each changed file and print its content
        for file in $CHANGED_FILES; do
          echo "Changed file: $file"
          echo "-----------------"
          cat $file  # Print the content of the changed file
          echo ""
        done
      else
        echo "No changes in the repository."
      fi

  - label: ":pipeline: Echo provided environment variable"
    command: |
      if [ -z "$ENV" ]; then
        echo "Error: ENV is not provided."
        exit 1
      else
        echo "The value of ENV is: $MY_VARIABLE"
      fi
    env:
      MY_VARIABLE: "${MY_VARIABLE}"
