steps:
  - label: ":pipeline: Check for changes in folder"
    command: |
      FOLDER="/tests"  # Replace this with your actual folder path
      if [ ! -d "$FOLDER" ]; then
        echo "Error: $FOLDER does not exist or is not a directory."
        exit 1
      fi

      if git diff --quiet HEAD~1 HEAD -- "$FOLDER"; then
        echo "No changes in $FOLDER"
        exit 0
      else
        echo "Changes detected in $FOLDER"
        # You can add additional commands to handle changes here
      fi

  - label: ":pipeline: Echo provided environment variable"
    command: |
      if [ -z "$ENV" ]; then
        echo "Error: ENV is not provided."
        exit 1
      else
        echo "The value of ENV is: $MY_VARIABLE"
      fi
    env:
      MY_VARIABLE: "${MY_VARIABLE}"
