steps:
  - label: ":pipeline: Echo provided environment variable"
    command: |
      if [ -z "$ENV" ]; then
        echo "Error: ENV is not provided."
        exit 1
      else
        echo "The value of ENV is: $MY_VARIABLE"
      fi
    env:
      MY_VARIABLE: "${MY_VARIABLE}"
